### ISSUE TITLE
Not a fan of the main class only being called Client

### ISSUE THREAD

**Issue by Hoaas** [nickfrederiksen/PasswordTester#1]
Perhaps not an issue ... but I would prefer if the class was called something a bit more specific.

Also not a fan of my old(est) password being in the database 13 times. 😢

**Comment by nickfrederiksen** [comment]
The code was written quite fast, and my initial commit had publics and privates all screwed up.

I thought the name `Client` would be an accurate name, since it is a client. But I see your point.

How about `PasswordTester.Password.Test("password")`? (Full namespace included for clarity).

**Comment by Hoaas** [comment]
¯\\\_(ツ)\_/¯
Maybe. 

Or perhaps
PasswordTesterClient? (maybe too long?)
PwTestClient? (too cryptic?)
PassCheckClient?
PasswordClient?
TroyHuntClient?
WillIBePwndClient?

I don't know :| Names are hard.

**Comment by nickfrederiksen** [comment]
I love "WillIBePwndClient", but I think it must be a bit shorter...😊

"PasswordTesterClient" is a bit long, but maybe something different, like "PasswordLookup" and rename the method to "Lookup"?
