### ISSUE TITLE
Dispose of the HttpResponse

### ISSUE THREAD

**Issue by RichardD2** [nickfrederiksen/PasswordTester#4]
The `HttpResponse` class implements `IDisposable`, suggesting that it needs to be disposed of.

One side-effect of not disposing the response: if you're using a `WebRequestHandler` with caching enabled, the response will only be cached when you call `Dispose()`.

```
using (var response = await httpClient.GetAsync(url).ConfigureAwait(false))
{
    await ParseResponse(response, hash, subStr).ConfigureAwait(false);
}
```

**Comment by nickfrederiksen** [comment]
Hehe... missed that when prototyping.
